[project]
name = "flixopt-app"
version = "0.1.0"
description = "A STreamlit app for the usage of flixopt"
requires-python = ">=3.11"
dependencies = [
    "flixopt[full]>=2.1.1",
    "streamlit>=1.45.1",
    "watchdog>=6.0.0",
]
