[project]
name = "flixopt-app"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flixopt>=2.1.1",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "plotly>=6.1.0",
    "streamlit>=1.45.1",
    "watchdog>=6.0.0",
]
